#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

app_name="minigalnano"
# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app_name
if [ ! $? -eq 0 ]; then
    exit 1
fi

# Install packages
packages='php5-fpm php5-gd'
export DEBIAN_FRONTEND=noninteractive                                                                                         

sudo apt-get --assume-yes --force-yes install ${packages}

if [ $? -ne 0 ]; then
	sudo apt-get update
	sudo apt-get --assume-yes --force-yes install ${packages}
fi

# Copy files to the right place
final_path=/var/www/$app_name
sudo mkdir -p $final_path/photos
sudo install -D -o root -g root -m 0644 ../sources/minigalnano.sources/* $final_path
sudo install -o www-data -g www-data -m 0644 ../conf/example.jpg $final_path/photos/

# Manage nginx conf
sudo install -o root -g root -m 0644 ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app_name.conf
sudo sed "s|<TPL:PATHTOCHANGE>|$path|g" -i /etc/nginx/conf.d/$domain.d/$app_name.conf 
sudo sed "s|<TPL:NAMETOCHANGE>|$app_name|g" -i /etc/nginx/conf.d/$domain.d/$app_name.conf 

# Manage php-fpm
sudo install -o root -g root -m 0644 ../conf/phpfpm_minigalnano.conf /etc/php5/fpm/pool.d/$app_name.conf
sudo sed "s|<TPL:PHP_NAME>|${app_name}_admin|g" -i /etc/php5/fpm/pool.d/$app_name.conf
sudo sed 's|<TPL:PHP_USER>|admin|g' -i /etc/php5/fpm/pool.d/$app_name.conf
sudo sed 's|<TPL:PHP_GROUP>|admins|g' -i /etc/php5/fpm/pool.d/$app_name.conf
sudo sed "s|<TPL:NGINX_REALPATH>|/var/www/${app_name}/|g" -i /etc/php5/fpm/pool.d/$app_name.conf

# Set default inits
sudo systemctl enable php5-fpm
sudo systemctl restart php5-fpm

sudo systemctl reload nginx

sudo yunohost app ssowatconf
