#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a minigalnano
if [ ! $? -eq 0 ]; then
    exit 1
fi

# Copy files to the right place
final_path=/var/www$path
sudo mkdir -p $final_path
sudo cp -a ../sources/minigalnano.sources/* $final_path

# Manage nginx conf
sudo cp -a ../conf/nginx.conf /etc/nginx/conf.d/$domain.d$path.conf
sudo sed "s|<TPL:PATHTOCHANGE>|$path|g" -i /etc/nginx/conf.d/$domain.d$path.conf 




# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf
