#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a gallery
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Copy files to the right place
final_path=/var/www/minigalnano
sudo mkdir -p $final_path
sudo cp -a ../sources/minigalnano $final_path

# Manage nginx conf
sudo cp -a ../conf/nginx.conf /etc/nginx/conf.d/gallery

# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf
