#!/bin/bash

# MinigalNano app for YunoHost 
# Copyright (C) 2015 Petit <petit@peccadilles.net>
# Contribute at https://github.com/petit42/minigalnano_ynh
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Retrieve arguments
domain=$1
path=$2
title=$3

sudo yunohost app setting nomapp title -v $title 

app_name="minigalnano"
# Copy files to the right place
final_path=/var/www/$app_name
sudo rm -rf $final_path

# Manage nginx conf
sudo rm /etc/nginx/conf.d/$domain.d/$app_name.conf

# Manage php-fpm
sudo rm /etc/php5/fpm/pool.d/$app_name.conf

# Set default inits
sudo systemctl restart php5-fpm
sudo systemctl reload nginx

